name: Deploy React App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build

      - run: ls -la build

      - name: Deploy to GitHub Pages
        run: |
          npm install -g gh-pages
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          gh-pages -d build -u "github-actions <github-actions@github.com>" -t ${{ secrets.GITHUB_TOKEN }}
